---
title: "About"
---

This website is composed in the [RStudio IDE](https://posit.co/download/rstudio-desktop/), as [R code](https://en.wikipedia.org/wiki/R_(programming_language)) authored as a [Quarto](https://quarto.org/) notebooks. With Quarto it is easy to render multiple report formats such as a PDF document or this website. In this case the report format is a [web site hosted at Quarto.pub](https://libjohn.quarto.pub/intro2r-datafestduke/). The code for this workshop and this webpage are all part of a single RStudio project that can be [found in a GitHub repository](https://github.com/libjohn/tutorial_intro2r_datafest). The code-along exercises for this workshop are in the GitHub repository but they are not part of the web site. You can work through the exercises by first downloading the GitHub repository. Then find the exercises within the `_exercises` directory.

This introductory workshop is workshop is taught by the [Center for Data and Visualization Sciences](https://library.duke.edu/data) in support of [Duke's DataFest](https://dukestatsci.github.io/datafest/).

For more information or resource on learning R, please visit the [Rfun learning series](https://Rfun.library.duke.edu).
